---
extends: default

ignore: |
  node_modules/
  dist/
  build/
  .git/
  **/*.md

rules:
  # Line-length is intentionally disabled. Modern wide screens and YAML's
  # common use of long strings (Jinja2 templates, URLs, SSH arguments, etc.)
  # make a hard line limit counterproductive. Use block scalars (| or >) for
  # readability where it makes sense, but not as a strict enforcement.
  line-length: disable
  document-start:
    present: true
    level: error
  truthy:
    allowed-values: ["true", "false"]
    level: error
  indentation:
    spaces: 2
    indent-sequences: true
    level: error
  trailing-spaces:
    level: error
  empty-lines:
    max: 2
    level: error
  new-line-at-end-of-file:
    level: error
